In [1]:
import numpy as np

n_people = 10
n_features = 2
data = np.random.choice(2, size=[n_people, n_features])

from randomised_response import rp_binary
rp_binary(data, 0.1)

                 

array([[0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [1, 1]])

In [10]:
true_mean = np.mean(data,axis=0)

In [13]:
epsilon = np.linspace(0,1/2)
error = epsilon.copy()
for i in range(len(error)):
    error[i] = sum(abs(true_mean - np.mean(rp_binary(data, epsilon[i]), axis=0)))    

In [14]:
error

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
abs(x - x)

array([0, 0])