In [88]:
import tensorflow_probability as tfp
tfd = tfp.distributions

In [93]:
b3 = tfd.Bernoulli(probs=[.3, .5, .7])
b3.prob([1,1,0])
b3_joint = tfd.Independent(b3, reinterpreted_batch_ndims=1)
b3_joint

<tfp.distributions.Independent 'IndependentBernoulli' batch_shape=[] event_shape=[3] dtype=int32>

In [81]:
jdn = tfd.JointDistributionNamed({
    'theta': tfd.Beta(concentration0=1, concentration1=1),
    'x_t': lambda theta : tfd.Independent(
        tfd.Bernoulli(probs=theta)
    )
})
# can't get reinterpreted_batch_ndims=1 to work

In [82]:
jdn.sample(2) # take two samples

{'theta': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.21225196, 0.5448272 ], dtype=float32)>,
 'x_t': <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>}

In [83]:
jdn.sample(1)['x_t'] # take one sample, get only 'x_t'

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>

In [84]:
# Estimation

In [85]:
# Generate data
import numpy as np
xs = np.random.choice(2,size=100)

In [86]:
def target_log_prob(model, theta):
    return model.log_prob(theta=theta, x_t = xs)


In [87]:
target_log_prob(jdn, 0.7) # this is the probability of X_s

ValueError: reinterpreted_batch_ndims(1) cannot exceed distribution.batch_ndims(0)